// Generated by dts-bundle-generator v9.5.1

export declare function health(): Promise<{
	status: string;
	timestamp: string;
	db: string;
	env: "development" | "production";
}>;
export declare function botStatus(): Promise<{
	connected: boolean;
	uptime: number;
	activeSessions: number;
	username: string | null;
}>;
/**
 * Send a message to a Discord user's DMs.
 * Callable by any agent or RPC consumer on this computer.
 *
 * userId is required. Set DISCORD_OWNER_ID in .env to enable owner-targeted agent calls.
 */
export declare function sendToDiscord(input: {
	message: string;
	userId?: string;
	imageUrls?: string[];
}): Promise<{
	success: boolean;
	error?: string;
}>;
/**
 * Get recent Discord conversation history for a user.
 */
export declare function getDiscordHistory(input?: {
	userId?: string;
	limit?: number;
}): Promise<{
	role: string;
	content: string;
	timestamp: string;
}[]>;

export {};
